### ISSUE TITLE
23w06a(23w07a) support

### ISSUE THREAD

**Issue by xllifi** [mt1006/mc-nbtac-mod#1]
any chance for latest snapshot support? i really want that mod for snapshots since they added a lot of technical stuff

**Comment by mt1006** [comment]
I'm not planning to regularly make versions for snapshots. As for current snapshot, maybe this weekend.

**Comment by xllifi** [comment]
if you're gonna do that please add support for entity tags

**Comment by mt1006** [comment]
If you mean entity NBT tags, they are supported

**Comment by mt1006** [comment]
Also as I tested, 1.19.3 version works fine with newest snapshot (23w07a). It has some problems with detecting exactly what are types of tags for these new "display" entities but this is caused by a general imperfection in detecting types and it will be improved in future versions.
