### ISSUE TITLE
Mod not working as intended in multiplayer

### ISSUE THREAD

**Issue by Julienraptor01** [mt1006/mc-nbtac-mod#12]
The mod doesn't seem to work in multiplayer
here we can see it working in solo
![image](https://github.com/mt1006/mc-nbtac-mod/assets/49841713/9925d8ea-483c-4383-a2e0-bf88b4e3d376)
but if i join a multiplayer server, i get no suggestion
![image](https://github.com/mt1006/mc-nbtac-mod/assets/49841713/c43ae45a-db15-4854-b562-b79e7f1f7ad0)

**Comment by mt1006** [comment]
It's a client-side mod, so have you installed it on the client? If so, I will check it next week, as I'm currently not at home.

**Comment by Julienraptor01** [comment]
> It's a client-side mod, so have you installed it on the client? If so, I will check it next week, as I'm currently not at home.

yes, the 1st screenshot show it working

a weird thing is that it seems like the suggestion for /summon does work but all the others don't in multiplayer

**Comment by mt1006** [comment]
Ok, as I wrote, I'll check it next week.

**Comment by mt1006** [comment]
I tried to reproduce the problem, but it works fine for me. Maybe there's some conflicting mod.

![2023-08-14_21 25 41](https://github.com/mt1006/mc-nbtac-mod/assets/34820479/4a43c646-47e0-4596-a240-26535c419871)

**Comment by Julienraptor01** [comment]
fine, i guess i'll do some debug on my side to try and see what other mod is breaking it...
i'll tell you once i found the issue so it can be fixed

**Comment by mt1006** [comment]
I just found that it may be caused by Polymer

**Comment by mt1006** [comment]
I'll take a closer look at this

**Comment by mt1006** [comment]
It should work now, not the most elegant solution but works. I'll release a new version in a few days as I would also like to update dependencies. Anyway, thanks for reporting.

**Comment by Julienraptor01** [comment]
> It should work now, not the most elegant solution but works. I'll release a new version in a few days as I would also like to update dependencies. Anyway, thanks for reporting.

np, also thanks you for updating, your mod is a very helpful one
