### ISSUE TITLE
My instance crashes when i turn on your mod while starting. Plz help

### ISSUE THREAD

**Issue by SinedKadis** [mt1006/mc-nbtac-mod#15]
[api.mclo.gs_1_raw_a1SJyQN.txt](https://github.com/mt1006/mc-nbtac-mod/files/12885362/api.mclo.gs_1_raw_a1SJyQN.txt)

**Comment by mt1006** [comment]
Unfortunately I don't see any stack traces or even errors that could cause this behavior. Make sure you sent me a proper log or if there are any other logs that you could send me. Maybe try to send me a new one. In worst case you would need to send me the entire modpack or find a mod that is in conflict with mine.

**Comment by SinedKadis** [comment]
https://modrinth.com/modpack/modclient
here is my modpack without NBT Autocomplete, add it by yourself

**Comment by mt1006** [comment]
Thanks, I was able to recreate a crash. I'll try to fix it soon.
