### ISSUE TITLE
Update for 1.20.5 components

### ISSUE THREAD

**Issue by FrogFlavouredWater** [mt1006/mc-nbtac-mod#19]
As NBT data has been changed to components, will this be changed to support them? Flags are still not autocompleted.

For example in the new system, to give an enchanted iron sword it would be:

/give @s minecraft:iron_sword[minecraft:enchantments={sharpness:1, unbreaking:3}]
                                                                                       ^^^^^^^^^^^^^^^^
                                                                                       This section does not get autofilled

It would be a great help to anyone trying to use these commands.

**Comment by mt1006** [comment]
I have plans on adding support for them. I don't know to which extent they'll be required, as there maybe some changes in the next snapshots, but for now I was thinking about:
- adding type names for components,
- hiding (or moving to the bottom of the list, when I'll add custom suggestion sorting) components that are not applicable to the specific item, as currently from what I've seen it suggest every existing component for every item,
- adding suggestions for these component NBTs (or whatever they're called now), like in your example.

It will probably take some time to implement all of these, and I won't have much of it until the end of May, so version with support for new item components will be released probably in June at the earliest. I don't know if I'll even have time to port my mods before the end of May to the new version. I personally hope they won't release 1.20.5 and just go straight into releasing 1.21 in the summer.

**Comment by Cuteistfox** [comment]
>  I personally hope they won't release 1.20.5 and just go straight into releasing 1.21 in the summer.

well 1.20.6 is already out

**Comment by mt1006** [comment]
Yup, it should be released as 1.21. I guess the fact that it's 1.20.6 and not 1.20.5 is the best proof that releasing snapshots as stable releases wasn't the mojang's smartest idea. As for NBTac I'll start working on a new version probably closer the end of this month.

**Comment by itsarian** [comment]
> Yup, it should be released as 1.21. I guess the fact that it's 1.20.6 and not 1.20.5 is the best proof that releasing snapshots as stable releases wasn't the mojang's smartest idea. As for NBTac I'll start working on a new version probably closer the end of this month.

any updates?

**Comment by mt1006** [comment]
I'm working on an update. It should be ready this month.

**Comment by KirillStudios** [comment]
Hey will the update for this be anytime soon.

**Comment by mt1006** [comment]
It should be ready this week
