### ISSUE TITLE
Bug in latest version (Fabric)

### ISSUE THREAD

**Issue by TheWaffleLord** [mt1006/mc-nbtac-mod#2]
Found a bug in v4-1.1 (Fabric) (1.19.4)
If you move around anything in the resource pack menu and click done, when the loading bar reaches the end the screen doesn't fade out and let you back into the game like normal, it just hangs there and forces you to Alt+F4 to get out.

Here's my log file if that helps:
[latest.log](https://github.com/mt1006/mc-nbtac-mod/files/11404188/latest.log)

**Comment by mt1006** [comment]
Ok, I found the issue. Thanks for reporting. I'll release a patch soon.
