### ISSUE TITLE
[Feature] Wiki Page for commands

### ISSUE THREAD

**Issue by SpyCoder77** [mt1006/mc-nbtac-mod#20]
You should make a button next to the autocomplete that has the wiki page for it.

**Comment by mt1006** [comment]
I don't think it's even possible, as NBT tags don't have their separate pages. On each entity page there's just list of available tags with short descriptions.

Edit: I'm talking about minecraft.wiki ofc

**Comment by mt1006** [comment]
I could theoretically add short descriptions for each tag, but:
1. tags for entities and block entities are mostly dynamically generated and not predefined, thanks to that they don't require too much updating
2. it would be too much work, even if I would copy everything from minecraft.wiki

**Comment by SpyCoder77** [comment]
You could just add a button that takes you too the link. Also, I don't fully understand number 1.

**Comment by mt1006** [comment]
That would have to be a link to the entire entity page, so you would have to find tag in it anyway.

As for point 1, suggestions for items are predefined in resource files, but suggestions for entities and block entities aren't. In short, when first running mod it disassembles Minecraft code in search of NBT related method calls and that way it knows the tag names and types. To give some additional suggestions, like automatic entity id suggestions there are also predefined predictions in resource files which are responsible for fixing some missing tags and these additional suggestions (subtypes).

**Comment by SpyCoder77** [comment]
Ok, I understand.

**Comment by mt1006** [comment]
As I said earlier, I may some day add it, but that won't be soon. I also see a need for some form of tag descriptions, but I also don't see an easy way I could add them.

**Comment by SpyCoder77** [comment]
You could just have a very long json. That would be very hard and tedious
to make though.
