### ISSUE TITLE
Missing suggestions related to "translate

### ISSUE THREAD

**Issue by jasminexs** [mt1006/mc-nbtac-mod#21]

**Comment by jasminexs** [comment]
i accidentally pressed enter too early but the problem is that the "fallback" json text component isnt suggested, it only works when the "translate" json component is provided

**Comment by mt1006** [comment]
You mean like for `display.Name` item component?

**Comment by jasminexs** [comment]
Anything that uses text; tellraw, title, display.Name, book pages

**Comment by mt1006** [comment]
Currently it only suggests `' "` (for NBT tags) to not confuse json text with normal text, but I have plans to add more complex suggestions for it, including `fallback` component (probably around version 1.4, as 1.3 will bring support for the new item components). Therefore, I'll keep this issue open.
