### ISSUE TITLE
CanPlaceOn tag missing

### ISSUE THREAD

**Issue by xllifi** [mt1006/mc-nbtac-mod#23]
![image](https://github.com/mt1006/mc-nbtac-mod/assets/70767436/a26920ed-5288-4c1c-9d58-d4f5b0a09f28)
Wiki: [Item Format](https://minecraft.wiki/w/Item_format) > Block Tags

**Comment by mt1006** [comment]
Fixed, I'll soon release a new version. Thanks for reporting

**Comment by GoldenTotem** [comment]
> Fixed, I'll soon release a new version. Thanks for reporting

could you please give this update to 1.16.5, thanks!
