### ISSUE TITLE
[Suggestion/Feature Request] Missing suggestion for  CustomPotionEffects  on tipped arrow

### ISSUE THREAD

**Issue by GoldenTotem** [mt1006/mc-nbtac-mod#24]
Minecraft  1.20.1  and  1.16.5
Mod nbtac  1.2.1  and 1.1.7

This command is correct ```/give @s minecraft:tipped_arrow{CustomPotionEffects:[{Id:3,Duration:500}]}``` but the suggestion is not given correctly.

![PixPin_2024-06-26_00-46-51](https://github.com/mt1006/mc-nbtac-mod/assets/70516358/7edabe53-99a4-4607-81fc-dc00180fc23e)

**Comment by GoldenTotem** [comment]
It seems that CustomPotionColor is forgotten. Both of us.

**Comment by mt1006** [comment]
Yup, it looks like I forgot about it. I'll fix it in the 1.3.1, sometime in the near future, but I won't backport it to 1.16.5.
