### ISSUE TITLE
[Suggestion/Feature Request] Missing suggestion for  Damage

### ISSUE THREAD

**Issue by GoldenTotem** [mt1006/mc-nbtac-mod#25]
Minecraft 1.16.5  Mod 1.1.7

![PixPin_2024-06-26_01-21-15](https://github.com/mt1006/mc-nbtac-mod/assets/70516358/d2983b36-e0f5-4e7a-b459-814365bc75f0)

**Comment by mt1006** [comment]
Ok, I've backported it to 1.16.5 as 1.1.9 (https://github.com/mt1006/mc-nbtac-mod/releases/tag/NBTac-1.1.9), as well as #23, but I don't plan to support 1.16.5 or 1.18.2 any longer.
Also thanks for reporting #24, which I've fixed in 1.1.9 and I'll add fix for newer versions in 1.3.
