### ISSUE TITLE
NBT Error: 1.20.5+

### ISSUE THREAD

**Issue by GithubMinecraft9212** [mt1006/mc-nbtac-mod#27]
The issue is for example, the enchantments. They don't show up. Starting 1.20.5, Mojang has changed the syntax on almost EVERY command including NBT. And It seems that this mod's code is currently outdated due to the issues not only for the /give command but on the commands the use nbt. Just like the /summon command. And most of the time, the autocomplete just, does not show up.

Before 1.20.5
/give @s cobblestone{display:{Name:'["",{"text":"Sus Stone","italic":false}]'},Enchantments:[{lvl:69,id:protection},{lvl:69,id:thorns}]}
After 1.20.5
/give @s cobblestone[custom_name='["",{"text":"Sus Stone","italic":false}]',enchantments={levels:{protection:69,thorns:69}}]

**Comment by mt1006** [comment]
Mod supports 1.20.5 item components and additional suggestions should show up for them (at least they show up on Fabric 1.21 with version 1.3.1). Tell which exact version you are using (mc version, modloader and mod version).

**Comment by GithubMinecraft9212** [comment]
I use
1.21.0
Fabric 0.15.11

I will be back tommorow. My laptop is about to die.

**Comment by mt1006** [comment]
Tell for what exactly command there are no suggestions. Also, if you're using any mods other than NBTac and Fabric API, try without them, and if it fixes the issue, try to find which mod caused it.

**Comment by GithubMinecraft9212** [comment]
As far as I've tested, the enchantments for /give and the entity data in /summon.

**Comment by mt1006** [comment]
It works for me. Do you have any other mods installed?

![img](https://github.com/user-attachments/assets/d99f7c68-7eaa-48c1-8182-c41e200fb2ad)

**Comment by GithubMinecraft9212** [comment]
https://modrinth.com/collection/yXmXu5jp You can check my mod collection.

**Comment by GithubMinecraft9212** [comment]
By the way, Immersive Portals is just there. I have not installed it yet.

**Comment by mt1006** [comment]
I've installed all mods from this collection on Fabric 1.21 including Melody required by FancyMenu and excluding Immersive Portals and WorldEditCUI which doesn't support 1.21, and suggestions still work fine.
If possible, send for what exactly command suggestions doesn't work (e.g. `/give @p minecraft:dirt[enchantments={levels:{`) as well as Minecraft logs. Also try disabling all resource packs and restarting the game.

**Comment by GithubMinecraft9212** [comment]
Huh, maybe the device? I use MacOS 14. I'll try this again next time.

**Comment by mt1006** [comment]
Maybe, but it still seems weird. As I said, if possible, send Minecraft logs.

**Comment by GithubMinecraft9212** [comment]
Also, I have OptiFabric installed, [for no reason cuz I use optifine and it ain't available on 1.21]

**Comment by GithubMinecraft9212** [comment]
Also, try to use v1.3.1 instead of v1.3.2. Maybe that helps? I still have no hands on my laptop yet.

**Comment by mt1006** [comment]
1.3.2 is only for Forge as it fixes bug present only on it. As for optifabric it isn't available on 1.20.6 or 1.21 so it couldn't cause this issue. If you mean the modpack with the same name, I tried it with mods from your collection and it also has no issues. When you'll have your laptop back, please send logs.

**Comment by mt1006** [comment]
Do you have your laptop now?

**Comment by GithubMinecraft9212** [comment]
Yes, and its resolved. Sorry for the late reply.

**Comment by mt1006** [comment]
Ok, good to hear
