### ISSUE TITLE
NBT Autocomplete mod can't get block entity classes when paired with Lithium

### ISSUE THREAD

**Issue by Kichura** [mt1006/mc-nbtac-mod#28]
When installing NBT Autocomplete with Lithium together on an 1.21 instance, The NBT autocomplete mod will spit multiple errors complaining about block entity classes being unable to be found.

The error logs can be found [here](https://pastebin.com/raw/jxNiQqEb).

**Comment by mt1006** [comment]
Fixed, thanks for reporting
