### ISSUE TITLE
Axolotl Variant NBT

### ISSUE THREAD

**Issue by shotadft** [mt1006/mc-nbtac-mod#29]
"Variant" tag does not appear on NBT for bucket with Axolotl and Axolotl spawn eggs.

**Comment by shotadft** [comment]
If possible, we would like to have a fix for past versions.

**Comment by mt1006** [comment]
Thanks for reporting, I'll try to fix it soon. From what I've checked this issue applies only to buckets, as variant for spawn eggs is defined inside `EntityTag`. As for backports, I'll backport it to 1.19.2 and 1.20.1.

**Comment by shotadft** [comment]
thx.

**Comment by shotadft** [comment]
> As for backports, I'll backport it to 1.19.2 and 1.20.1.

I'm playing Version1.20.4. So I hope you will backport it to 1.20.4 as well!

**Comment by mt1006** [comment]
Ok, I'll release a patch in a few days.

**Comment by shotadft** [comment]
thx!
