### ISSUE TITLE
Missing suggestion for /scoreboard players display styled

### ISSUE THREAD

**Issue by BarbTurnip437** [mt1006/mc-nbtac-mod#35]
Minecraft 1.21.1
Mod nbtac 1.3.6

This command is correct 
```mcfunction
scoreboard players display numberformat Cbscfe test styled {"obfuscated":true}
```
but the suggestion is not given correctly.
![屏幕截图 2024-11-09 135931](https://github.com/user-attachments/assets/c7e1e324-6a18-415f-b55a-0beabc67de81)

**Comment by mt1006** [comment]
I'll fix it soon. Thanks for reporting.
