### ISSUE TITLE
Missing suggestion for Item Modifier and Predicate

### ISSUE THREAD

**Issue by BarbTurnip437** [mt1006/mc-nbtac-mod#38]
in the commands
```mcfunction
item modify entity @a weapon.mainhand 
```
and
```mcfunction
execute as @a if predicate 
```
suggestions stop popping out

**Comment by mt1006** [comment]
You mean that without NBTac they were working fine?

**Comment by BarbTurnip437** [comment]
no
just means there no suggestions
I have bad english qwq

**Comment by mt1006** [comment]
If it isn't issue caused by NBTac and missing suggestions aren't related to NBT data or JSON text components, then it isn't issue. Also, do you have any datapacks with predicates or item modifiers installed? AFAIK there aren't any in vanilla datapack.
