### ISSUE TITLE
Need NBTac-FABRIC-1.21-1.3.9.jar

### ISSUE THREAD

**Issue by zhjc2021** [mt1006/mc-nbtac-mod#40]
Since some other mods support 1.21.1 but not 1.21, I am still using the 1.21 client. 
I tried to modify the fabric.mod.json in your NBTac-FABRIC-1.21.1-1.3.9.jar to make the mod support 1.21, but it failed. 
If you have time, can you make a 1.21 version of NBTac-FABRIC-1.3.9?

**Comment by mt1006** [comment]
Ok, I'll soon release 1.21 version
