### ISSUE TITLE
Suggestion: Also put the autocomplete tags when using the 'nbt=' selector argument

### ISSUE THREAD

**Issue by donutStudio** [mt1006/mc-nbtac-mod#41]
This mod is so useful for commands, especially when /summoning and /giving items. But it's always a headache when I have to detect people with @a[nbt={...}] and its pretty annoying to not get the autocomplete there. (especially because I got so used to having this autocomplete during other commands)

Thanks!

**Comment by mt1006** [comment]
For me it gives autocompletion (Fabric 1.21.1, NBTac 1.3.9). Is it issue specific for multiplayer or some other version?

![img](https://github.com/user-attachments/assets/01ce5981-fe6f-4772-8c4b-6d2625d7782f)

**Comment by donutStudio** [comment]
It could be multiplayer- im on fabric 1.21.3, and I use it on a Purpur server if that helps- I have not tested this in singleplayer

**Comment by mt1006** [comment]
Ok, I was able to recreate this issue. For some reason it was working fine on a Fabric server, but had issues working on a Purpur server. I'll take a closer look at the cause and try to fix it next week.

**Comment by mt1006** [comment]
Anyway, thanks for reporting
