### ISSUE TITLE
I specified potion_contents as per autocomplete, but it says it's an invalid component format.

### ISSUE THREAD

**Issue by KozukiYOMA** [mt1006/mc-nbtac-mod#42]
![image](https://github.com/user-attachments/assets/4cea4549-180c-44df-a3de-d56eb7c386e6)
![image](https://github.com/user-attachments/assets/4451e6bc-de7e-409c-bd0f-871b784fb43e)
![image](https://github.com/user-attachments/assets/6ca0b181-9567-48c0-bec9-2fd1d70c4110)

FabricLoader 0.16.9-1.21.3
FabricAPI 0.110.0+1.21.3

**Comment by mt1006** [comment]
I'll fix it soon (probably on Sunday or Monday). Thanks for reporting.
