### ISSUE TITLE
Doesn't work on the server

### ISSUE THREAD

**Issue by arushenst** [mt1006/mc-nbtac-mod#7]
I have permission

**Comment by mt1006** [comment]
It's client-side mod.

**Comment by mt1006** [comment]
Have you not installed it on the client or is it a problem with the mod?

**Comment by arushenst** [comment]
> It's client-side mod.

😢 it's a pity
mod problem i think

**Comment by mt1006** [comment]
I don't think it would be even possible to implement this mod on server-side only as suggestions are handled on the client.
